In [1]:
import pandas as pd

In [2]:
import pyodbc
server = '' 
database = '' 
username = '' 
password = ''
cnxn = pyodbc.connect('DRIVER={ODBC Driver 17 for SQL Server};SERVER='+server+';DATABASE='+database+';UID='+username+';PWD='+ password)
cursor = cnxn.cursor()

In [3]:
# DF ALL DAP & KCL FROM Pengadaan_ME2N
df_all_leadtime = pd.read_sql_query("SELECT * FROM (SELECT Pengadaan_ME2N.BANFN,Pengadaan_ME2N.BNFPO,Pengadaan_ME2N.EBELN,Pengadaan_ME2N.EBELP, Pengadaan_EKBE.BUDAT,Pengadaan_ME5A_R1.BADAT, Pengadaan_ME2N.EMATN, Pengadaan_ME2N.TXZ01, Pengadaan_ME2N.WERKS, BDA_MARC.BSTMI AS LOTSIZE, BDA_MARC.EISBE AS SAFETYSTOCK FROM Pengadaan_ME2N LEFT JOIN Pengadaan_ME5A_R1 ON Pengadaan_ME2N.BANFN = Pengadaan_ME5A_R1.BANFN AND Pengadaan_ME2N.BNFPO = Pengadaan_ME5A_R1.BNFPO LEFT JOIN Pengadaan_EKBE ON Pengadaan_EKBE.EBELN = Pengadaan_ME2N.EBELN AND Pengadaan_EKBE.EBELP = Pengadaan_ME2N.EBELP LEFT JOIN BDA_MARC ON BDA_MARC.MATNR = Pengadaan_ME2N.EMATN AND BDA_MARC.WERKS = Pengadaan_ME2N.WERKS WHERE (Pengadaan_EKBE.BWART = '101' OR Pengadaan_EKBE.BWART = '103') AND Pengadaan_ME2N.EMATN LIKE '000000000006%' AND Pengadaan_ME2N.BANFN IS NOT NULL AND BDA_MARC.MAABC = 'A') AS TBL1 WHERE BADAT IS NOT NULL ORDER BY BANFN, BNFPO, EBELN",cnxn)

In [4]:
df_c = df_all_leadtime
df_c

,BANFN,BNFPO,EBELN,EBELP,BUDAT,BADAT,EMATN,TXZ01,WERKS,LOTSIZE,SAFETYSTOCK
0,2200000000,00010,5100005579,00010,20160902,20160224,000000000006130910,"SEAL,MECH:BALANCED;50MM;CARB/SC/VITON",B601,0.0,0.0
1,2200000009,00020,5100005213,00020,20160803,20160516,000000000006124779,"BLADE,IMPELLER,FAN:68MM;350MM;PLASTIC",B601,0.0,0.0
2,2200000019,00020,5100012450,00010,20161124,20160906,000000000006133329,"VALVE,GATE:1IN;800LB;THD;BB;OSY;A105",B601,0.0,0.0
3,2200000030,00010,5100002174,00010,20161109,20160111,000000000006124009,"COVER,BEARING:CARGOTEC VST-640W UNLOADER",B601,40.0,0.0
4,2200000030,00020,5100002174,00020,20161109,20160111,000000000006121449,BEARING AND SHAFT:BMH VST-640W UNLOADER,B601,10.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
60210,2600033347,00020,5500028370,00010,20220323,20211220,000000000006082738,STUDBOLT:3/4IN UNCX180MM;B7;NUT-2H,F601,0.0,0.0
60211,2600033347,00030,5500028370,00020,20220323,20211220,000000000006082789,STUDBOLT:7/8IN UNCX125MM;B7;NUT-2H,F601,0.0,0.0
60212,2600033347,00040,5500028370,00030,20220323,20211220,000000000006082793,STUDBOLT:7/8IN UNCX245MM;B7;NUT-2H,F601,0.0,0.0
60213,2600033347,00050,5500028335,00010,20220406,20211220,000000000006082800,STUDBOLT:1-1/8IN UNCX190MM;B7;NUT-2H,F601,0.0,0.0
60214,2600033422,00010,5500028421,00010,20220321,20211225,000000000006086434,CONBEXTRA GP (SEMEN),F601,0.0,0.0

In [5]:
# buat cek duplicate
df_c[df_c.duplicated(subset=['BANFN','BNFPO','EBELN','EBELP'])]

,BANFN,BNFPO,EBELN,EBELP,BUDAT,BADAT,EMATN,TXZ01,WERKS,LOTSIZE,SAFETYSTOCK
16,2200000056,00050,5100005712,00010,20160928,20160125,000000000006119711,FILTER-CLOTH-5050X12090MM-POLYPROPYLENE,B601,36.0,0.0
18,2200000056,00060,5100006326,00010,20161129,20160517,000000000006119709,FILTER CLOTH;2134X1049X3950MM;PE,B601,100.0,0.0
28,2200000090,00020,5100017392,00010,20170131,20160627,000000000006123730,"COUPLING,FLEX:CHAIN;32-80X141.2MM;3880NM",B601,0.0,0.0
43,2200000130,00020,5100003803,00020,20160624,20160224,000000000006130936,"SEAL,MECH:MAZDA UO-2004MMS PUMP",B601,0.0,0.0
44,2200000130,00020,5100003803,00020,20160621,20160224,000000000006130936,"SEAL,MECH:MAZDA UO-2004MMS PUMP",B601,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
60180,2600032840,00020,5000001632,00020,20220214,20211103,000000000006162306,"INK,PRINT,CART:MAKE UP INK;UX-D160W",F601,0.0,0.0
60181,2600032840,00020,5000001632,00020,20220214,20211103,000000000006162306,"INK,PRINT,CART:MAKE UP INK;UX-D160W",F601,0.0,0.0
60183,2600032840,00030,5000001632,00030,20220214,20211103,000000000006161709,CLEANING SOLVENT BAG CODING PRINTER,F601,0.0,0.0
60184,2600032840,00030,5000001632,00030,20220214,20211103,000000000006161709,CLEANING SOLVENT BAG CODING PRINTER,F601,0.0,0.0
60194,2600033037,00020,5500028286,00010,20220210,20211123,000000000006080749,"TIMBER,HARDWOOD:MERANTI;5X25X400CM;GR 3",F601,0.0,0.0

In [6]:
df_c.drop_duplicates(subset =['BANFN','BNFPO','EBELN','EBELP','BUDAT','BADAT'],inplace=True)

In [7]:
df_c['BUDAT'] = df_c['BUDAT'].str[:4] + '-' + df_c['BUDAT'].str[4:6] + '-' + df_c['BUDAT'].str[6:8]
df_c['BADAT'] = df_c['BADAT'].str[:4] + '-' + df_c['BADAT'].str[4:6] + '-' + df_c['BADAT'].str[6:8]

In [8]:
df_c

,BANFN,BNFPO,EBELN,EBELP,BUDAT,BADAT,EMATN,TXZ01,WERKS,LOTSIZE,SAFETYSTOCK
0,2200000000,00010,5100005579,00010,2016-09-02,2016-02-24,000000000006130910,"SEAL,MECH:BALANCED;50MM;CARB/SC/VITON",B601,0.0,0.0
1,2200000009,00020,5100005213,00020,2016-08-03,2016-05-16,000000000006124779,"BLADE,IMPELLER,FAN:68MM;350MM;PLASTIC",B601,0.0,0.0
2,2200000019,00020,5100012450,00010,2016-11-24,2016-09-06,000000000006133329,"VALVE,GATE:1IN;800LB;THD;BB;OSY;A105",B601,0.0,0.0
3,2200000030,00010,5100002174,00010,2016-11-09,2016-01-11,000000000006124009,"COVER,BEARING:CARGOTEC VST-640W UNLOADER",B601,40.0,0.0
4,2200000030,00020,5100002174,00020,2016-11-09,2016-01-11,000000000006121449,BEARING AND SHAFT:BMH VST-640W UNLOADER,B601,10.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
60210,2600033347,00020,5500028370,00010,2022-03-23,2021-12-20,000000000006082738,STUDBOLT:3/4IN UNCX180MM;B7;NUT-2H,F601,0.0,0.0
60211,2600033347,00030,5500028370,00020,2022-03-23,2021-12-20,000000000006082789,STUDBOLT:7/8IN UNCX125MM;B7;NUT-2H,F601,0.0,0.0
60212,2600033347,00040,5500028370,00030,2022-03-23,2021-12-20,000000000006082793,STUDBOLT:7/8IN UNCX245MM;B7;NUT-2H,F601,0.0,0.0
60213,2600033347,00050,5500028335,00010,2022-04-06,2021-12-20,000000000006082800,STUDBOLT:1-1/8IN UNCX190MM;B7;NUT-2H,F601,0.0,0.0
60214,2600033422,00010,5500028421,00010,2022-03-21,2021-12-25,000000000006086434,CONBEXTRA GP (SEMEN),F601,0.0,0.0

In [9]:
df_c['BUDAT'] = pd.to_datetime(df_c['BUDAT'])

In [10]:
df_c.drop(df_c[df_c['BADAT'] ==  '4752-12-08'].index, inplace=True)

In [11]:
df_c['BADAT'] = pd.to_datetime(df_c['BADAT'])

# Cek duplicate tanggal dan ambil tanggal max

In [12]:
df_c[df_c['BANFN'] == '2200000056']

,BANFN,BNFPO,EBELN,EBELP,BUDAT,BADAT,EMATN,TXZ01,WERKS,LOTSIZE,SAFETYSTOCK
12,2200000056,00010,5100005693,00010,2016-09-28,2016-01-25,000000000006119710,HEMYHYDRATE FILTER -- FILTER-CLOTH-2108,B601,234.0,0.0
13,2200000056,00020,5100005679,00010,2016-10-14,2016-01-25,000000000006109659,FILTER ELMNT:CLOTH;2360X11060MM;50UM;PP,B601,8.0,0.0
14,2200000056,00030,5100005724,00010,2016-09-28,2016-01-25,000000000006124978,FILTER-CLOTCH-2800 X 35700 MM-POLYPROPYL,B601,10.0,0.0
15,2200000056,00050,5100005712,00010,2016-10-14,2016-01-25,000000000006119711,FILTER-CLOTH-5050X12090MM-POLYPROPYLENE,B601,36.0,0.0
16,2200000056,00050,5100005712,00010,2016-09-28,2016-01-25,000000000006119711,FILTER-CLOTH-5050X12090MM-POLYPROPYLENE,B601,36.0,0.0
17,2200000056,00060,5100006326,00010,2016-11-18,2016-05-17,000000000006119709,FILTER CLOTH;2134X1049X3950MM;PE,B601,100.0,0.0
18,2200000056,00060,5100006326,00010,2016-11-29,2016-05-17,000000000006119709,FILTER CLOTH;2134X1049X3950MM;PE,B601,100.0,0.0

In [13]:
# Untuk BUDAT kata mas ghifari diambil nilai min
# kenapa ga max.
c = df_c.groupby(['BANFN','BNFPO','EBELN','EBELP']).agg({'BUDAT' : 'max'}).reset_index()

In [14]:
c[c['BANFN'] == '2200000056']

         BANFN  BNFPO       EBELN  EBELP      BUDAT
12  2200000056  00010  5100005693  00010 2016-09-28
13  2200000056  00020  5100005679  00010 2016-10-14
14  2200000056  00030  5100005724  00010 2016-09-28
15  2200000056  00050  5100005712  00010 2016-10-14
16  2200000056  00060  5100006326  00010 2016-11-29

In [15]:
final = pd.merge(df_c,c,on=['BANFN','BNFPO','EBELN','EBELP','BUDAT'])

In [16]:
final[final['BANFN'] == '2200000056']

,BANFN,BNFPO,EBELN,EBELP,BUDAT,BADAT,EMATN,TXZ01,WERKS,LOTSIZE,SAFETYSTOCK
12,2200000056,00010,5100005693,00010,2016-09-28,2016-01-25,000000000006119710,HEMYHYDRATE FILTER -- FILTER-CLOTH-2108,B601,234.0,0.0
13,2200000056,00020,5100005679,00010,2016-10-14,2016-01-25,000000000006109659,FILTER ELMNT:CLOTH;2360X11060MM;50UM;PP,B601,8.0,0.0
14,2200000056,00030,5100005724,00010,2016-09-28,2016-01-25,000000000006124978,FILTER-CLOTCH-2800 X 35700 MM-POLYPROPYL,B601,10.0,0.0
15,2200000056,00050,5100005712,00010,2016-10-14,2016-01-25,000000000006119711,FILTER-CLOTH-5050X12090MM-POLYPROPYLENE,B601,36.0,0.0
16,2200000056,00060,5100006326,00010,2016-11-29,2016-05-17,000000000006119709,FILTER CLOTH;2134X1049X3950MM;PE,B601,100.0,0.0

# Search Leadtime

In [17]:
final['LEADTIME'] = (final['BUDAT'] - final['BADAT']).dt.days

In [18]:
final

,BANFN,BNFPO,EBELN,EBELP,BUDAT,BADAT,EMATN,TXZ01,WERKS,LOTSIZE,SAFETYSTOCK,LEADTIME
0,2200000000,00010,5100005579,00010,2016-09-02,2016-02-24,000000000006130910,"SEAL,MECH:BALANCED;50MM;CARB/SC/VITON",B601,0.0,0.0,191
1,2200000009,00020,5100005213,00020,2016-08-03,2016-05-16,000000000006124779,"BLADE,IMPELLER,FAN:68MM;350MM;PLASTIC",B601,0.0,0.0,79
2,2200000019,00020,5100012450,00010,2016-11-24,2016-09-06,000000000006133329,"VALVE,GATE:1IN;800LB;THD;BB;OSY;A105",B601,0.0,0.0,79
3,2200000030,00010,5100002174,00010,2016-11-09,2016-01-11,000000000006124009,"COVER,BEARING:CARGOTEC VST-640W UNLOADER",B601,40.0,0.0,303
4,2200000030,00020,5100002174,00020,2016-11-09,2016-01-11,000000000006121449,BEARING AND SHAFT:BMH VST-640W UNLOADER,B601,10.0,0.0,303
...,...,...,...,...,...,...,...,...,...,...,...,...
53862,2600033347,00020,5500028370,00010,2022-03-23,2021-12-20,000000000006082738,STUDBOLT:3/4IN UNCX180MM;B7;NUT-2H,F601,0.0,0.0,93
53863,2600033347,00030,5500028370,00020,2022-03-23,2021-12-20,000000000006082789,STUDBOLT:7/8IN UNCX125MM;B7;NUT-2H,F601,0.0,0.0,93
53864,2600033347,00040,5500028370,00030,2022-03-23,2021-12-20,000000000006082793,STUDBOLT:7/8IN UNCX245MM;B7;NUT-2H,F601,0.0,0.0,93
53865,2600033347,00050,5500028335,00010,2022-04-06,2021-12-20,000000000006082800,STUDBOLT:1-1/8IN UNCX190MM;B7;NUT-2H,F601,0.0,0.0,107
53866,2600033422,00010,5500028421,00010,2022-03-21,2021-12-25,000000000006086434,CONBEXTRA GP (SEMEN),F601,0.0,0.0,86

In [19]:
final[final['EMATN'] == '000000000006017742']

,BANFN,BNFPO,EBELN,EBELP,BUDAT,BADAT,EMATN,TXZ01,WERKS,LOTSIZE,SAFETYSTOCK,LEADTIME
34027,2400003460,00060,5300006877,00060,2017-04-28,2016-10-21,000000000006017742,PACKING MATERIAL:SQ;1/2IN;ASBESTOS-PTFE,D601,15.0,5.0,189
40732,2400015097,00090,5300037044,00090,2021-06-14,2020-03-24,000000000006017742,PACKING MATERIAL:SQ;1/2IN;ASBESTOS-PTFE,D601,15.0,5.0,447

In [23]:
final

,BANFN,BNFPO,EBELN,EBELP,BUDAT,BADAT,EMATN,TXZ01,WERKS,LOTSIZE,SAFETYSTOCK,LEADTIME
0,2200000000,00010,5100005579,00010,2016-09-02,2016-02-24,000000000006130910,"SEAL,MECH:BALANCED;50MM;CARB/SC/VITON",B601,0.0,0.0,191
1,2200000009,00020,5100005213,00020,2016-08-03,2016-05-16,000000000006124779,"BLADE,IMPELLER,FAN:68MM;350MM;PLASTIC",B601,0.0,0.0,79
2,2200000019,00020,5100012450,00010,2016-11-24,2016-09-06,000000000006133329,"VALVE,GATE:1IN;800LB;THD;BB;OSY;A105",B601,0.0,0.0,79
3,2200000030,00010,5100002174,00010,2016-11-09,2016-01-11,000000000006124009,"COVER,BEARING:CARGOTEC VST-640W UNLOADER",B601,40.0,0.0,303
4,2200000030,00020,5100002174,00020,2016-11-09,2016-01-11,000000000006121449,BEARING AND SHAFT:BMH VST-640W UNLOADER,B601,10.0,0.0,303
...,...,...,...,...,...,...,...,...,...,...,...,...
53862,2600033347,00020,5500028370,00010,2022-03-23,2021-12-20,000000000006082738,STUDBOLT:3/4IN UNCX180MM;B7;NUT-2H,F601,0.0,0.0,93
53863,2600033347,00030,5500028370,00020,2022-03-23,2021-12-20,000000000006082789,STUDBOLT:7/8IN UNCX125MM;B7;NUT-2H,F601,0.0,0.0,93
53864,2600033347,00040,5500028370,00030,2022-03-23,2021-12-20,000000000006082793,STUDBOLT:7/8IN UNCX245MM;B7;NUT-2H,F601,0.0,0.0,93
53865,2600033347,00050,5500028335,00010,2022-04-06,2021-12-20,000000000006082800,STUDBOLT:1-1/8IN UNCX190MM;B7;NUT-2H,F601,0.0,0.0,107
53866,2600033422,00010,5500028421,00010,2022-03-21,2021-12-25,000000000006086434,CONBEXTRA GP (SEMEN),F601,0.0,0.0,86

In [20]:
final.groupby(['WERKS','EMATN','TXZ01']).agg({'LEADTIME' : 'min'})

                                                                   LEADTIME
WERKS EMATN              TXZ01
B601  000000000006001276 BEARING,BALL:DG;1R;85X180X41MM;C3                8
      000000000006002041 BELT,V:5V1250;125IN OC;0.62X0.54IN;WEDGE        37
      000000000006013855 MAGNET WIRE:0.80MM;CLASS F;ENAMEL;CU            58
      000000000006020217 BEARING,RLR,SA:SPHER;100X215X73MM;C3;CYL        14
      000000000006034114 ADAPTER,BEARING:THD;75X85X110X63MM              39
...                                                                     ...
F601  000000000006168474 BOLT,MACHINE:M12X35MM;HEX;DUPLX;DP28W          105
      000000000006168534 PIPE:2INX6M;S40;TP304;SMLS;PE                  110
      000000000006169027 MOTOR,AC:3PH;4P;0.9KW;400V;VIBRATING            48
      000000000006173832 BEARING UNIT,BALL:SQ FLANGED;UCF208            215
      000000000006174838 FILTER ELMNT:OIL;CARTD;10UM;SS;INDUFIL         129

[12598 rows x 1 columns]

In [22]:
final.groupby(['WERKS','EMATN','TXZ01']).agg({'LEADTIME' : 'max'})

                                                                   LEADTIME
WERKS EMATN              TXZ01
B601  000000000006001276 BEARING,BALL:DG;1R;85X180X41MM;C3              193
      000000000006002041 BELT,V:5V1250;125IN OC;0.62X0.54IN;WEDGE        92
      000000000006013855 MAGNET WIRE:0.80MM;CLASS F;ENAMEL;CU            65
      000000000006020217 BEARING,RLR,SA:SPHER;100X215X73MM;C3;CYL        80
      000000000006034114 ADAPTER,BEARING:THD;75X85X110X63MM              39
...                                                                     ...
F601  000000000006168474 BOLT,MACHINE:M12X35MM;HEX;DUPLX;DP28W          301
      000000000006168534 PIPE:2INX6M;S40;TP304;SMLS;PE                  226
      000000000006169027 MOTOR,AC:3PH;4P;0.9KW;400V;VIBRATING           358
      000000000006173832 BEARING UNIT,BALL:SQ FLANGED;UCF208            216
      000000000006174838 FILTER ELMNT:OIL;CARTD;10UM;SS;INDUFIL         141

[12598 rows x 1 columns]

# export excel

In [24]:
final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 53867 entries, 0 to 53866
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   BANFN        53867 non-null  object
 1   BNFPO        53867 non-null  object
 2   EBELN        53867 non-null  object
 3   EBELP        53867 non-null  object
 4   BUDAT        53867 non-null  datetime64[ns]
 5   BADAT        53867 non-null  datetime64[ns]
 6   EMATN        53867 non-null  object
 7   TXZ01        53867 non-null  object
 8   WERKS        53867 non-null  object
 9   LOTSIZE      53867 non-null  float64
 10  SAFETYSTOCK  53867 non-null  float64
 11  LEADTIME     53867 non-null  int64
dtypes: datetime64[ns](2), float64(2), int64(1), object(7)
memory usage: 5.3+ MB

In [28]:
# final = final.astype(str)
final = final.reset_index(drop = True)
# final.to_csv('LEADTIME_120522.csv', index=False)